[app]
ip = "127.0.0.1"
port = 5000

## 日志
[log]
channel = "block"   # 分类
level = 1           # 级别 1:debug  2:warn 3:info 4:error 5:panic
output = "D://Log"         # 日志输出 不配置(默认stdout) 配置文件路劲
stack = false        # 是否打印堆栈信息

[Chain]
address = "http://47.109.29.166:8488"
wsAddress = "ws://47.109.29.166:8588"
nftContractOwnKey = "df7abadcc169e4a2a8ffdd32852f6fb34da033ed4abfa01fddecdc7aad9f0ec2"
nftContractAddress = "0x7aD8b67FAb5E77da46D23CcFc54C95c82927eFDf"
toAddress = "0x1D6d8c0ec7FF4E03d0Be661e5007B177daB9F69d"

[Java]
mintUrl = "http://192.168.50.15:10313/nft/mintSucceed"
type = "application/json"